apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpapp
  name: phpapp
  namespace: default
spec:
  clusterIP: 10.106.210.237
  clusterIPs:
  - 10.106.210.237
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31994
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: phpapp
  sessionAffinity: None
  type: NodePort
